
classdef Odometry < ros.Message
    %Odometry MATLAB implementation of quadrotor_msgs/Odometry
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/Odometry' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '94d99f86002b25504a5d3354fa1ad709' % The MD5 Checksum of the message definition
        PropertyList = { 'Curodom' 'Kfodom' 'Kfid' 'Status' } % List of non-constant message properties
        ROSPropertyList = { 'curodom' 'kfodom' 'kfid' 'status' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.nav_msgs.Odometry' ...
            'ros.msggen.nav_msgs.Odometry' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        STATUSODOMVALID = uint8(0)
        STATUSODOMINVALID = uint8(1)
        STATUSODOMLOOPCLOSURE = uint8(2)
    end
    properties
        Curodom
        Kfodom
        Kfid
        Status
    end
    methods
        function set.Curodom(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.nav_msgs.Odometry'};
            validateattributes(val, validClasses, validAttributes, 'Odometry', 'Curodom')
            obj.Curodom = val;
        end
        function set.Kfodom(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.nav_msgs.Odometry'};
            validateattributes(val, validClasses, validAttributes, 'Odometry', 'Kfodom')
            obj.Kfodom = val;
        end
        function set.Kfid(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odometry', 'Kfid');
            obj.Kfid = uint32(val);
        end
        function set.Status(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Odometry', 'Status');
            obj.Status = uint8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.Odometry.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.Odometry(strObj);
        end
    end
end
