
classdef Serial < ros.Message
    %Serial MATLAB implementation of quadrotor_msgs/Serial
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/Serial' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e448fb7595af9a8adfcab5ec241c7d4f' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Channel' 'Type' 'Data' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'channel' 'type' 'data' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        SO3CMD = uint8(115)
        TRPYCMD = uint8(112)
        STATUSDATA = uint8(99)
        OUTPUTDATA = uint8(100)
        PPROUTPUTDATA = uint8(116)
        PPRGAINS = uint8(103)
    end
    properties
        Header
        Channel
        Type
        Data
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'Serial', 'Header')
            obj.Header = val;
        end
        function set.Channel(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Serial', 'Channel');
            obj.Channel = uint8(val);
        end
        function set.Type(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Serial', 'Type');
            obj.Type = uint8(val);
        end
        function set.Data(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = uint8.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'Serial', 'Data');
            obj.Data = uint8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.Serial.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.Serial(strObj);
        end
    end
end
