
classdef SO3Command < ros.Message
    %SO3Command MATLAB implementation of quadrotor_msgs/SO3Command
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/SO3Command' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'a466650b2633e768513aa3bf62383c86' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Force' 'Orientation' 'Aux' 'KR' 'KOm' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'force' 'orientation' 'aux' 'kR' 'kOm' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msg.geometry_msgs.Quaternion' ...
            'ros.msggen.quadrotor_msgs.AuxCommand' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Force
        Orientation
        Aux
        KR
        KOm
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'SO3Command', 'Header')
            obj.Header = val;
        end
        function set.Force(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'SO3Command', 'Force')
            obj.Force = val;
        end
        function set.Orientation(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.geometry_msgs.Quaternion'};
            validateattributes(val, validClasses, validAttributes, 'SO3Command', 'Orientation')
            obj.Orientation = val;
        end
        function set.Aux(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.quadrotor_msgs.AuxCommand'};
            validateattributes(val, validClasses, validAttributes, 'SO3Command', 'Aux')
            obj.Aux = val;
        end
        function set.KR(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'SO3Command', 'KR');
            obj.KR = double(val);
        end
        function set.KOm(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'SO3Command', 'KOm');
            obj.KOm = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.SO3Command.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.SO3Command(strObj);
        end
    end
end
