
classdef StatusData < ros.Message
    %StatusData MATLAB implementation of quadrotor_msgs/StatusData
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/StatusData' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'c70a4ec4725273263ae176ad30f89553' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'LoopRate' 'Voltage' 'Seq' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'loop_rate' 'voltage' 'seq' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        LoopRate
        Voltage
        Seq
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'StatusData', 'Header')
            obj.Header = val;
        end
        function set.LoopRate(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'StatusData', 'LoopRate');
            obj.LoopRate = uint16(val);
        end
        function set.Voltage(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'StatusData', 'Voltage');
            obj.Voltage = double(val);
        end
        function set.Seq(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'StatusData', 'Seq');
            obj.Seq = uint8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.StatusData.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.StatusData(strObj);
        end
    end
end
