
classdef TRPYCommand < ros.Message
    %TRPYCommand MATLAB implementation of quadrotor_msgs/TRPYCommand
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/TRPYCommand' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '6779ee8a86cc757aeea21725df32d00c' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Aux' 'Thrust' 'Roll' 'Pitch' 'Yaw' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'aux' 'thrust' 'roll' 'pitch' 'yaw' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.quadrotor_msgs.AuxCommand' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Aux
        Thrust
        Roll
        Pitch
        Yaw
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'TRPYCommand', 'Header')
            obj.Header = val;
        end
        function set.Aux(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.quadrotor_msgs.AuxCommand'};
            validateattributes(val, validClasses, validAttributes, 'TRPYCommand', 'Aux')
            obj.Aux = val;
        end
        function set.Thrust(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'TRPYCommand', 'Thrust');
            obj.Thrust = single(val);
        end
        function set.Roll(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'TRPYCommand', 'Roll');
            obj.Roll = single(val);
        end
        function set.Pitch(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'TRPYCommand', 'Pitch');
            obj.Pitch = single(val);
        end
        function set.Yaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'TRPYCommand', 'Yaw');
            obj.Yaw = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.TRPYCommand.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.TRPYCommand(strObj);
        end
    end
end
