
classdef AuxCommand < ros.Message
    %AuxCommand MATLAB implementation of quadrotor_msgs/AuxCommand
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/AuxCommand' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '94f75840e4b1e03675da764692f2c839' % The MD5 Checksum of the message definition
        PropertyList = { 'CurrentYaw' 'KfCorrection' 'AngleCorrections' 'EnableMotors' 'UseExternalYaw' } % List of non-constant message properties
        ROSPropertyList = { 'current_yaw' 'kf_correction' 'angle_corrections' 'enable_motors' 'use_external_yaw' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        CurrentYaw
        KfCorrection
        AngleCorrections
        EnableMotors
        UseExternalYaw
    end
    methods
        function set.CurrentYaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'AuxCommand', 'CurrentYaw');
            obj.CurrentYaw = double(val);
        end
        function set.KfCorrection(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'AuxCommand', 'KfCorrection');
            obj.KfCorrection = double(val);
        end
        function set.AngleCorrections(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 2};
            validateattributes(val, validClasses, validAttributes, 'AuxCommand', 'AngleCorrections');
            obj.AngleCorrections = double(val);
        end
        function set.EnableMotors(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'AuxCommand', 'EnableMotors');
            obj.EnableMotors = logical(val);
        end
        function set.UseExternalYaw(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'AuxCommand', 'UseExternalYaw');
            obj.UseExternalYaw = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.AuxCommand.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.AuxCommand(strObj);
        end
    end
end
