
classdef Corrections < ros.Message
    %Corrections MATLAB implementation of quadrotor_msgs/Corrections
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/Corrections' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '61e86887a75fe520847d3256306360f5' % The MD5 Checksum of the message definition
        PropertyList = { 'KfCorrection' 'AngleCorrections' } % List of non-constant message properties
        ROSPropertyList = { 'kf_correction' 'angle_corrections' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        KfCorrection
        AngleCorrections
    end
    methods
        function set.KfCorrection(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Corrections', 'KfCorrection');
            obj.KfCorrection = double(val);
        end
        function set.AngleCorrections(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 2};
            validateattributes(val, validClasses, validAttributes, 'Corrections', 'AngleCorrections');
            obj.AngleCorrections = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.Corrections.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.Corrections(strObj);
        end
    end
end
