
classdef Gains < ros.Message
    %Gains MATLAB implementation of quadrotor_msgs/Gains
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/Gains' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'b82763b9f24e5595e2a816aa779c9461' % The MD5 Checksum of the message definition
        PropertyList = { 'Kp' 'Kd' 'KpYaw' 'KdYaw' } % List of non-constant message properties
        ROSPropertyList = { 'Kp' 'Kd' 'Kp_yaw' 'Kd_yaw' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Kp
        Kd
        KpYaw
        KdYaw
    end
    methods
        function set.Kp(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Gains', 'Kp');
            obj.Kp = double(val);
        end
        function set.Kd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Gains', 'Kd');
            obj.Kd = double(val);
        end
        function set.KpYaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Gains', 'KpYaw');
            obj.KpYaw = double(val);
        end
        function set.KdYaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Gains', 'KdYaw');
            obj.KdYaw = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.Gains.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.Gains(strObj);
        end
    end
end
