
classdef LQRTrajectory < ros.Message
    %LQRTrajectory MATLAB implementation of quadrotor_msgs/LQRTrajectory
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/LQRTrajectory' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '46be446c56bc8bf131978edfc4464480' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'TrajectoryId' 'Action' 'R' 'StartYaw' 'FinalYaw' 'S0' 'Ut' 'Sf' 'TF' 'DebugInfo' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'trajectory_id' 'action' 'r' 'start_yaw' 'final_yaw' 's0' 'ut' 'sf' 't_f' 'debug_info' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        ACTIONADD = uint32(1)
        ACTIONABORT = uint32(2)
        ACTIONWARNSTART = uint32(3)
        ACTIONWARNFINAL = uint32(4)
        ACTIONWARNIMPOSSIBLE = uint32(5)
    end
    properties
        Header
        TrajectoryId
        Action
        R
        StartYaw
        FinalYaw
        S0
        Ut
        Sf
        TF
        DebugInfo
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'LQRTrajectory', 'Header')
            obj.Header = val;
        end
        function set.TrajectoryId(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'LQRTrajectory', 'TrajectoryId');
            obj.TrajectoryId = uint32(val);
        end
        function set.Action(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'LQRTrajectory', 'Action');
            obj.Action = uint32(val);
        end
        function set.R(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'LQRTrajectory', 'R');
            obj.R = double(val);
        end
        function set.StartYaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'LQRTrajectory', 'StartYaw');
            obj.StartYaw = double(val);
        end
        function set.FinalYaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'LQRTrajectory', 'FinalYaw');
            obj.FinalYaw = double(val);
        end
        function set.S0(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 6};
            validateattributes(val, validClasses, validAttributes, 'LQRTrajectory', 'S0');
            obj.S0 = double(val);
        end
        function set.Ut(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'LQRTrajectory', 'Ut');
            obj.Ut = double(val);
        end
        function set.Sf(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 6};
            validateattributes(val, validClasses, validAttributes, 'LQRTrajectory', 'Sf');
            obj.Sf = double(val);
        end
        function set.TF(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'LQRTrajectory', 'TF');
            obj.TF = double(val);
        end
        function set.DebugInfo(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'LQRTrajectory', 'DebugInfo');
            obj.DebugInfo = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.LQRTrajectory.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.LQRTrajectory(strObj);
        end
    end
end
