
classdef OutputData < ros.Message
    %OutputData MATLAB implementation of quadrotor_msgs/OutputData
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/OutputData' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '5759ee97fd5c090dcdccf7fc3e50d024' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Orientation' 'AngularVelocity' 'LinearAcceleration' 'MagneticField' 'LoopRate' 'Voltage' 'PressureDheight' 'PressureHeight' 'RadioChannel' 'Seq' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'orientation' 'angular_velocity' 'linear_acceleration' 'magnetic_field' 'loop_rate' 'voltage' 'pressure_dheight' 'pressure_height' 'radio_channel' 'seq' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msg.geometry_msgs.Quaternion' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Orientation
        AngularVelocity
        LinearAcceleration
        MagneticField
        LoopRate
        Voltage
        PressureDheight
        PressureHeight
        RadioChannel
        Seq
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'OutputData', 'Header')
            obj.Header = val;
        end
        function set.Orientation(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.geometry_msgs.Quaternion'};
            validateattributes(val, validClasses, validAttributes, 'OutputData', 'Orientation')
            obj.Orientation = val;
        end
        function set.AngularVelocity(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'OutputData', 'AngularVelocity')
            obj.AngularVelocity = val;
        end
        function set.LinearAcceleration(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'OutputData', 'LinearAcceleration')
            obj.LinearAcceleration = val;
        end
        function set.MagneticField(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'OutputData', 'MagneticField')
            obj.MagneticField = val;
        end
        function set.LoopRate(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OutputData', 'LoopRate');
            obj.LoopRate = uint16(val);
        end
        function set.Voltage(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OutputData', 'Voltage');
            obj.Voltage = double(val);
        end
        function set.PressureDheight(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OutputData', 'PressureDheight');
            obj.PressureDheight = double(val);
        end
        function set.PressureHeight(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OutputData', 'PressureHeight');
            obj.PressureHeight = double(val);
        end
        function set.RadioChannel(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 8};
            validateattributes(val, validClasses, validAttributes, 'OutputData', 'RadioChannel');
            obj.RadioChannel = uint8(val);
        end
        function set.Seq(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OutputData', 'Seq');
            obj.Seq = uint8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.OutputData.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.OutputData(strObj);
        end
    end
end
