
classdef PolynomialTrajectory < ros.Message
    %PolynomialTrajectory MATLAB implementation of quadrotor_msgs/PolynomialTrajectory
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/PolynomialTrajectory' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '3abb6e1147f95babc52b64612c5ba5ed' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'TrajectoryId' 'Action' 'NumOrder' 'NumSegment' 'StartYaw' 'FinalYaw' 'CoefX' 'CoefY' 'CoefZ' 'Time' 'MagCoeff' 'Order' 'DebugInfo' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'trajectory_id' 'action' 'num_order' 'num_segment' 'start_yaw' 'final_yaw' 'coef_x' 'coef_y' 'coef_z' 'time' 'mag_coeff' 'order' 'debug_info' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        ACTIONADD = uint32(1)
        ACTIONABORT = uint32(2)
        ACTIONWARNSTART = uint32(3)
        ACTIONWARNFINAL = uint32(4)
        ACTIONWARNIMPOSSIBLE = uint32(5)
    end
    properties
        Header
        TrajectoryId
        Action
        NumOrder
        NumSegment
        StartYaw
        FinalYaw
        CoefX
        CoefY
        CoefZ
        Time
        MagCoeff
        Order
        DebugInfo
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'Header')
            obj.Header = val;
        end
        function set.TrajectoryId(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'TrajectoryId');
            obj.TrajectoryId = uint32(val);
        end
        function set.Action(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'Action');
            obj.Action = uint32(val);
        end
        function set.NumOrder(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'NumOrder');
            obj.NumOrder = uint32(val);
        end
        function set.NumSegment(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'NumSegment');
            obj.NumSegment = uint32(val);
        end
        function set.StartYaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'StartYaw');
            obj.StartYaw = double(val);
        end
        function set.FinalYaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'FinalYaw');
            obj.FinalYaw = double(val);
        end
        function set.CoefX(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'CoefX');
            obj.CoefX = double(val);
        end
        function set.CoefY(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'CoefY');
            obj.CoefY = double(val);
        end
        function set.CoefZ(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'CoefZ');
            obj.CoefZ = double(val);
        end
        function set.Time(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'Time');
            obj.Time = double(val);
        end
        function set.MagCoeff(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'MagCoeff');
            obj.MagCoeff = double(val);
        end
        function set.Order(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = uint32.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'Order');
            obj.Order = uint32(val);
        end
        function set.DebugInfo(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'PolynomialTrajectory', 'DebugInfo');
            obj.DebugInfo = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.PolynomialTrajectory.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.PolynomialTrajectory(strObj);
        end
    end
end
