
classdef PositionCommand < ros.Message
    %PositionCommand MATLAB implementation of quadrotor_msgs/PositionCommand
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/PositionCommand' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '4712f0609ca29a79af79a35ca3e3967a' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Position' 'Velocity' 'Acceleration' 'Yaw' 'YawDot' 'Kx' 'Kv' 'TrajectoryId' 'TrajectoryFlag' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'position' 'velocity' 'acceleration' 'yaw' 'yaw_dot' 'kx' 'kv' 'trajectory_id' 'trajectory_flag' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            'ros.msggen.geometry_msgs.Point' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        TRAJECTORYSTATUSEMPTY = uint8(0)
        TRAJECTORYSTATUSREADY = uint8(1)
        TRAJECTORYSTATUSCOMPLETED = uint8(3)
        TRAJECTROYSTATUSABORT = uint8(4)
        TRAJECTORYSTATUSILLEGALSTART = uint8(5)
        TRAJECTORYSTATUSILLEGALFINAL = uint8(6)
        TRAJECTORYSTATUSIMPOSSIBLE = uint8(7)
    end
    properties
        Header
        Position
        Velocity
        Acceleration
        Yaw
        YawDot
        Kx
        Kv
        TrajectoryId
        TrajectoryFlag
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'PositionCommand', 'Header')
            obj.Header = val;
        end
        function set.Position(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Point'};
            validateattributes(val, validClasses, validAttributes, 'PositionCommand', 'Position')
            obj.Position = val;
        end
        function set.Velocity(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'PositionCommand', 'Velocity')
            obj.Velocity = val;
        end
        function set.Acceleration(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'PositionCommand', 'Acceleration')
            obj.Acceleration = val;
        end
        function set.Yaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PositionCommand', 'Yaw');
            obj.Yaw = double(val);
        end
        function set.YawDot(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PositionCommand', 'YawDot');
            obj.YawDot = double(val);
        end
        function set.Kx(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'PositionCommand', 'Kx');
            obj.Kx = double(val);
        end
        function set.Kv(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'PositionCommand', 'Kv');
            obj.Kv = double(val);
        end
        function set.TrajectoryId(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PositionCommand', 'TrajectoryId');
            obj.TrajectoryId = uint32(val);
        end
        function set.TrajectoryFlag(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PositionCommand', 'TrajectoryFlag');
            obj.TrajectoryFlag = uint8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.PositionCommand.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.PositionCommand(strObj);
        end
    end
end
