
classdef PPROutputData < ros.Message
    %PPROutputData MATLAB implementation of quadrotor_msgs/PPROutputData
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'quadrotor_msgs/PPROutputData' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '732c0e3ca36f241464f8c445e78a0d0a' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'QuadTime' 'DesThrust' 'DesRoll' 'DesPitch' 'DesYaw' 'EstRoll' 'EstPitch' 'EstYaw' 'EstAngvelX' 'EstAngvelY' 'EstAngvelZ' 'EstAccX' 'EstAccY' 'EstAccZ' 'Pwm' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'quad_time' 'des_thrust' 'des_roll' 'des_pitch' 'des_yaw' 'est_roll' 'est_pitch' 'est_yaw' 'est_angvel_x' 'est_angvel_y' 'est_angvel_z' 'est_acc_x' 'est_acc_y' 'est_acc_z' 'pwm' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        QuadTime
        DesThrust
        DesRoll
        DesPitch
        DesYaw
        EstRoll
        EstPitch
        EstYaw
        EstAngvelX
        EstAngvelY
        EstAngvelZ
        EstAccX
        EstAccY
        EstAccZ
        Pwm
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'Header')
            obj.Header = val;
        end
        function set.QuadTime(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'QuadTime');
            obj.QuadTime = uint16(val);
        end
        function set.DesThrust(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'DesThrust');
            obj.DesThrust = double(val);
        end
        function set.DesRoll(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'DesRoll');
            obj.DesRoll = double(val);
        end
        function set.DesPitch(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'DesPitch');
            obj.DesPitch = double(val);
        end
        function set.DesYaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'DesYaw');
            obj.DesYaw = double(val);
        end
        function set.EstRoll(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'EstRoll');
            obj.EstRoll = double(val);
        end
        function set.EstPitch(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'EstPitch');
            obj.EstPitch = double(val);
        end
        function set.EstYaw(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'EstYaw');
            obj.EstYaw = double(val);
        end
        function set.EstAngvelX(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'EstAngvelX');
            obj.EstAngvelX = double(val);
        end
        function set.EstAngvelY(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'EstAngvelY');
            obj.EstAngvelY = double(val);
        end
        function set.EstAngvelZ(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'EstAngvelZ');
            obj.EstAngvelZ = double(val);
        end
        function set.EstAccX(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'EstAccX');
            obj.EstAccX = double(val);
        end
        function set.EstAccY(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'EstAccY');
            obj.EstAccY = double(val);
        end
        function set.EstAccZ(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'EstAccZ');
            obj.EstAccZ = double(val);
        end
        function set.Pwm(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 4};
            validateattributes(val, validClasses, validAttributes, 'PPROutputData', 'Pwm');
            obj.Pwm = uint16(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.quadrotor_msgs.PPROutputData.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.quadrotor_msgs.PPROutputData(strObj);
        end
    end
end
